config/routes.rb
Funtivity::Application.routes.draw do

  resources :activities
  root :to => redirect('/activities')

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @activity = Activity.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    @activities = Activity.all
  end

  def new
    # default: render 'new' template
  end

  def create
    @activity = Activity.create!(params[:activity])
    flash[:notice] = "#{@activity.title} was successfully created."
    redirect_to activities_path
  end

  def edit
    @activity = Activity.find params[:id]
  end

  def update
    @activity = Activity.find params[:id]
    @activity.update_attributes!(params[:activity])
    flash[:notice] = "#{@activity.title} was successfully updated."
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity = Activity.find params[:id]
    @activity.destroy
    flash[:notice] = "Activity '#{@activity.title}' deleted."
    redirect_to activities_path
  end
  
  private

  def act_params
    params.require(:activity).permit(:title, :act_type, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Activities

= form_tag activity_path(@activity), :method => :put do

  = label :activity, :title, 'Title'
  = text_field :activity, 'title'

  = label :activity, :act_type, 'Type'
  = select :activity, :act_type, ['Family','Dating','Friends','Free','Tourism']

  = label :activity, :description, 'Description'
  = text_area :activity, 'description'

  = submit_tag 'Update Activity Info'

app/views/activities/index.html.haml
-#  This file is app/views/activity/index.html.haml
%h1 All Activities

%table#activities
  %thead
    %tr
      %th Title
      %th Type
      %th More Info
  %tbody
    - @activities.each do |activity|
      %tr
        %td= activity.title 
        %td= activity.act_type
        %td= link_to "More about #{activity.title}", activity_path(activity)

= link_to 'Add new activity', new_activity_path

app/views/activities/new.html.haml
%h1 Create New Activity

= form_tag activities_path do

  = label :activity, :title, 'Title'
  = text_field :activity, 'title'

  = label :activity, :act_type, 'Type'
  = select :activity, :act_type, ['Family','Dating','Friends','Free','Tourism']
  = label :activity, :description, 'Description'
  = text_field :activity, 'description'

  = submit_tag 'Save Changes'

app/views/activities/show.html.haml
-# in app/views/activities/show.html.haml

%h2 Details about #{@activity.title}

%ul#details
  %li
    Type:
    = @activity.act_type
  %li
    Created on:
    = @activity.created_at.strftime("%B %d, %Y")
%h3 Description:

%p#description= @activity.description

= link_to 'Edit', edit_activity_path(@activity)
= button_to 'Delete', activity_path(@activity), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to activity list', activities_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funtivity</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>